export const APIMethods = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE"
}

export const MessageTypes = {
    ERROR: "ERROR",
    SUCCESS: "SUCCESS",
    WARNING: "WARNING"
}

export const AuthProviders = {
    FACEBOOK: "facebook.com",
    GOOGLE: "google.com"
}

export const RequestActionType = {
    SIGNUP: "SIGNUP",
    SIGNIN: "SIGNIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    GET_USER: "GET_USER",
    CREATE_ANIMAL: "CREATE_ANIMAL",
    UPDATE_ANIMAL: "UPDATE_ANIMAL",
    GET_ANIMAL: "GET_ANIMAL",
    DELETE_ANIMAL: "DELETE_ANIMAL",
    CREATE_SPECIE: "CREATE_ANIMAL",
    UPDATE_SPECIE: "UPDATE_ANIMAL",
    GET_SPECIE: "GET_ANIMAL",
    DELETE_SPECIE: "DELETE_ANIMAL",
    CREATE_BREED: "CREATE_BREED",
    UPDATE_BREED: "UPDATE_BREED",
    GET_BREED: "GET_BREED",
    DELETE_BREED: "DELETE_BREED",
    CREATE_SERVICE: "CREATE_SERVICE",
    UPDATE_SERVICE: "UPDATE_SERVICE",
    GET_SERVICE: "GET_SERVICE",
    DELETE_SERVICE: "DELETE_SERVICE",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    GET_PRODUCT: "GET_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    CREATE_SELL: "CREATE_SELL",
    UPDATE_SELL: "UPDATE_SELL",
    GET_SELL: "GET_SELL",
    DELETE_SELL: "DELETE_SELL",
}

export const UserActions = {
    ADD: "ADD",
    EDIT: "EDIT",
    DELETE: "DELETE"
}

export const UserProfiles = {
    ADMIN: "ADMINISTRADOR",
    CLIENTE: "CLIENTE",
    FUNCIONARIO: "FUNCIONARIO"
}

export const Services = {
    CONSULTA: "consulta",
    BANHO_E_TOSA: "banho e tosa"
}